import type { Metadata } from 'next';
import { amiko } from '../ui/font';
import '../globals.css';
import Header from '../components/Header';
import Footer from '../components/Footer';

export const metadata: Metadata = {
    title: 'AL Studio',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html className='m-0 h-full' lang='fr'>
            <body
                className={`${amiko.className} flex h-full flex-col bg-crema`}>
                <div className='fixed top-0 w-full'>
                    <Header />
                </div>
                <div className='mt-[162px] flex-1'>{children}</div>
                <Footer />
            </body>
        </html>
    );
}
