import type { Metadata } from 'next'
import { amiko } from './ui/font'
import './globals.css'

export const metadata: Metadata = {
  title: 'AL Studio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${amiko.className} bg-crema`}>{children}</body>
    </html>
  )
}
