import type { Metadata } from 'next';
import { amiko } from '../ui/font';
import '../globals.css';
import Header from '../components/Header';
import Footer from '../components/Footer';

export const metadata: Metadata = {
    title: 'AL Studio',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html className='h-full m-0' lang='en'>
            <body
                className={`${amiko.className} bg-crema flex flex-col h-full`}>
                <div className='fixed top-0 w-full'>
                    <Header />
                </div>
                <div className='flex-1 mt-[162px]'>{children}</div>
                <Footer />
            </body>
        </html>
    );
}
